name: ci-cd
on:
  push:
    branches: [ "main" ]
    paths:
      - "services/mcp-graph-svc/**"
      - "charts/mcp-graph-svc/**"
      - ".github/workflows/ci-cd.yaml"
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/mcp-graph-svc
  CONTEXT: services/mcp-graph-svc

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=ref,event=branch

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  bump-helm:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update helm values tag to commit SHA
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          sed -i "s#tag: \".*\"#tag: \"${IMAGE_TAG}\"#g" charts/mcp-graph-svc/values.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add charts/mcp-graph-svc/values.yaml
          git commit -m "bump image tag to ${IMAGE_TAG}" || echo "no changes"
          git push || true

